language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t ak0arjun/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ak0arjun/docker-react npm run test